{{- if .Values.database.deployInternalPostgres }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
    tier: database
spec:
  serviceName: {{ .Values.database.host }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
      tier: database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: DATABASE_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DATABASE_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.database.storage.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.database.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: {{ .Release.Name }}-postgres
    tier: database
{{- end }}
